### ISSUE TITLE
Request to add OAJ (Observatorio Astrofísico de Javalambre) to visplot.com Tool

### ISSUE THREAD

**Issue by arritrancos** [egafton/visplot#12]
Hi,
My name is Miguel Chioare and I'm technical astronomer at Observatorio Astrofísico de Javalambre, in Teruel.
I am writing to inquire about the possibility of adding our observatory to your visplot.com tool.
Here are the coordinates for the OAJ:
    Latitude: +40.0418
    Longitude: -1.0163
    Elevation: 1957 meters

We believe that adding our observatory to visplot.com would greatly benefit not only our institution but also other astronomers who rely on your tool for their work.

Please let us know if it would be possible to include the Javalambre Astrophysical Observatory in the visplot.com database. We are more than willing to provide any additional information or assistance needed for the integration process.

Thank you very much for considering our request. We look forward to your response.

Best regards,
Miguel Chioare

**Comment by egafton** [comment]
@arritrancos Thanks for the suggestion! OAJ added, please check that it works as intended.

**Comment by illarl** [comment]
Hola Chio!

¿Cómo estás?

We have added the OAJ with the information your provided, but we could add some more features like observation limits or a collision map if applicable. 

Let us know if you would like to add something else.

Illa

**Comment by arritrancos** [comment]
Hola Illa and Egafton,

Thank you both for your prompt response and for adding JPCam and the photo of our JST to visplot.com. I have discussed it with my colleagues, and we are sure to come up with several proposals for additional features.

Best regards,

Miguel Chioare
